stages:
  - deploy

deploy-to-local:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying Node.js API..."
    - rm -rf /home/ti/automacoesIts
    - cp -r $CI_PROJECT_DIR /home/ti/automacoesIts
    - cd /home/ti/automacoesIts
    - npm install
    - cd apis/
    - pm2 describe autoApi > /dev/null && pm2 restart autoApi || pm2 start server.js --name autoApi
  tags:
    - autoApiRunner